trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Maven@3

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'